# Generated by Django 4.2.21 on 2025-05-23 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='readme',
            field=models.TextField(blank=True),
        ),
    ]
